### ISSUE TITLE
Current reference polyfill returns `false` for `DOMException` instances

### ISSUE THREAD

**Issue by lionel-rowe** [tc39/proposal-is-error#16]
https://github.com/tc39/proposal-is-error/blob/33dd75bb6b2c4159cbe8b11bb6554bbf4de69cf8/polyfill.js#L5

`Object.prototype.toString.call(new DOMException())` gives `'[object DOMException]'`, so the condition returns `false`.

**Comment by ljharb** [comment]
That's true - the `polyfill` file doesn't belong in this repo at all.

See https://npmjs.com/error.iserror for a maximally correct polyfill.
