### ISSUE TITLE
Beware of false negatives

### ISSUE THREAD

**Issue by brodo** [tc39/proposal-is-error#5]
First, I am delighted that this proposal reached stage 1 recently. I implemented support for printing aggregated errors to the console in Jest and faced difficulties determining whether an object was an error. You may want to add this to the list of use cases. In that process, I learned about Node's `util.types.isNativeError(value)`, which you could add as prior work.

I also found out that several popular libraries and frameworks (e.g. [Axios](https://github.com/axios/axios/pull/5558)) create errors that are not returned by the `Error` constructor but merely are `instanceof Error`. You can find these libraries by [searching for `Error.call(this)`](https://sourcegraph.com/search?q=context:global+%28language:JavaScript+OR+language:TypeScript%29+content:%22Error.call%28this%29%22+count:1000000&patternType=standard&sm=0&groupBy=repo) on Sourcegraph. 

 That means that people will see the following behavior:

```js
const myError = { __proto__: Error.prototype };
console.log(Error.isError(myError)); // false
console.log(myError instanceof Error); // true 
```

This could confuse people. It might be worth including an `instanceof` check in Error.isError().

I've also written an [extensive article](https://juliand.ax/posts/detect-js-errors/) about how to test if an object is an error if people are interested.

**Comment by ljharb** [comment]
Thanks!

Those examples aren't native errors though, so the instanceof check would be wrong. Libraries like that need to do `class extends Error` if they want the native branding.
